# Formatting, linting and testing are set in tasks.py

## General settings for locals
const_tags:
  - &V false # verbose: optional
  - &AR true # always run: optional
  - &PF false # pass filenames

repos:
  # Python related hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: mixed-line-ending
        args:
          - --fix=lf
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args:
          - --maxkb=2048
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--without-hashes"]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.16.1
    hooks:
      - id: gitleaks
  # Local hooks for Python
  - repo: local
    hooks:
      - id: invoke-format
        name: formatting
        entry: invoke
        language: system
        args:
          - format
        pass_filenames: *PF
        always_run: *AR
        verbose: *V

      - id: invoke-lint
        name: lint
        entry: invoke
        language: system
        args:
          - lint
        pass_filenames: *PF
        always_run: *AR
        verbose: *V

      - id: invoke-test
        name: pytest
        entry: invoke
        language: system
        args:
          - test
        pass_filenames: *PF
        always_run: *AR
        verbose: *V
