name: Python test

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["{{cookiecutter.python_version}}"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python {{cookiecutter.python_version}}
        uses: actions/setup-python@v5
        with:
          python-version:
            - " {{cookiecutter.python_version}} "

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry setuptools anybadge wheel
          poetry install
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint
        run: poetry run invoke lint
      - name: Test
        run: poetry run invoke test

      - name: Upload coverage report
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-${{ github.run_number }}-${{ cookiecutter.python_version }}
          path: coverage.xml

      - name: Upload test report
        if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ github.run_number }}-${{ cookiecutter.python_version }}
          path: unit-test-report.xml
