name: Python test

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ">=3.11 <3.13"

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade poetry setuptools anybadge wheel
          poetry install
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint
        run: poetry run invoke lint
      - name: Test
        run: poetry run invoke test
